// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWwv25Yc_SCOPfjaQljA945YV325TF_mI',
    appId: '1:274903194377:web:d8df7a001fe3b942f451d8',
    messagingSenderId: '274903194377',
    projectId: 'watch-hub-51c7f',
    authDomain: 'watch-hub-51c7f.firebaseapp.com',
    storageBucket: 'watch-hub-51c7f.appspot.com',
    measurementId: 'G-WXMQ8ZEHDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ctHNuDcfAq_8RyXdlHpDB74BnE0WnRs',
    appId: '1:274903194377:android:8bdc9b0535e5f759f451d8',
    messagingSenderId: '274903194377',
    projectId: 'watch-hub-51c7f',
    storageBucket: 'watch-hub-51c7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa5NpvFNmPe0VE0-fDWUSmX_k7zk34EH0',
    appId: '1:274903194377:ios:19fe6259486985baf451d8',
    messagingSenderId: '274903194377',
    projectId: 'watch-hub-51c7f',
    storageBucket: 'watch-hub-51c7f.appspot.com',
    iosBundleId: 'com.example.eProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa5NpvFNmPe0VE0-fDWUSmX_k7zk34EH0',
    appId: '1:274903194377:ios:93a2478e1cb2389cf451d8',
    messagingSenderId: '274903194377',
    projectId: 'watch-hub-51c7f',
    storageBucket: 'watch-hub-51c7f.appspot.com',
    iosBundleId: 'com.example.eProject.RunnerTests',
  );
}
